from manim import *
import numpy as np

class Inicio(ThreeDScene):
    def construct(self):
        n = ValueTracker(0)
        m = ValueTracker(0)

        self.camera.background_color = "#262626"

        title = Text("Complex 3D Graphs of Functions")
        function = MathTex("f(","x","+","n","i",")","=","y","+","z","i")
        function[0].set_color(GREEN)
        function[1].set_color(BLUE)
        function[2].set_color(GREEN)
        function[3].set_color(TEAL)
        function[4].set_color(RED)
        function[5].set_color(GREEN)
        function[7].set_color(BLUE)
        function[9].set_color(BLUE)
        function[10].set_color(RED)

        func = MathTex(r"f(a)=").to_edge(UL)
        func[0][0:2].set_color(GREEN)
        func[0][2:3].set_color(PURPLE)
        func[0][3:4].set_color(GREEN)


        funcc = MathTex("f(","a",")","=","y","+","z","i")
        funcc[0].set_color(GREEN)
        funcc[1].set_color(PURPLE)
        funcc[2].set_color(GREEN)
        funcc[4].set_color(BLUE)
        funcc[6].set_color(BLUE)
        funcc[7].set_color(RED)

        setsm = MathTex("x",",","y",",","z",",","n",",","m","\in","\mathbb{R}").shift(DOWN).to_edge(UR)
        setsm[0].set_color(BLUE)
        setsm[2].set_color(BLUE)
        setsm[4].set_color(BLUE)
        setsm[6].set_color(TEAL)
        setsm[8].set_color(TEAL)
        setsm[10].set_color(GREEN)

        sets = MathTex("x",",","y",",","z",",","n","\in","\mathbb{R}").shift(DOWN)
        sets[0].set_color(BLUE)
        sets[2].set_color(BLUE)
        sets[4].set_color(BLUE)
        sets[6].set_color(TEAL)
        sets[8].set_color(GREEN)

        sett = MathTex("x",",","y",",","z",",","n","\in","\mathbb{R}").shift(DOWN).to_edge(UR)
        sett[0].set_color(BLUE)
        sett[2].set_color(BLUE)
        sett[4].set_color(BLUE)
        sett[6].set_color(TEAL)
        sett[8].set_color(GREEN)

        seta = MathTex("x","+","n","i","=","a")
        seta[0].set_color(BLUE)
        seta[2].set_color(TEAL)
        seta[3].set_color(RED)
        seta[5].set_color(PURPLE)

        setk = MathTex(r"\forall ","k","\in","\mathbb{Z}").to_edge(UR)
        setk[0].set_color(TEAL)
        setk[1].set_color(TEAL)
        setk[3].set_color(GREEN)

        setkl = MathTex(r"\forall ","k","\in","\{-1,0,1\}").to_edge(UR)
        setkl[0].set_color(TEAL)
        setkl[1].set_color(TEAL)
        setkl[3].set_color(GREEN)

        setkp = MathTex(r"\forall ","k","\in","\mathbb{Z}^+_0").to_edge(UR)
        setkp[0].set_color(TEAL)
        setkp[1].set_color(TEAL)
        setkp[3].set_color(GREEN)

        setkm = MathTex(r"\forall ","k","\in","\mathbb{Z}^-_0").to_edge(UR)
        setkm[0].set_color(TEAL)
        setkm[1].set_color(TEAL)
        setkm[3].set_color(GREEN)

        function2 = MathTex("f(a)=a").to_edge(UL).set_color(PURPLE)
        function2[0][0:2].set_color(GREEN)
        function2[0][2:3].set_color(PURPLE)
        function2[0][3:4].set_color(GREEN)
        function2[0][4:5].set_color(WHITE)

        self.wait(1)
        self.play(Write(title))
        self.play(title.animate.shift(UP*1.5))
        self.play(Write(function),run_time=2)
        self.wait(2)
        self.play(Write(sets),run_time=2)
        self.wait(2)
        self.play(Write(seta.next_to(sets,DOWN)),run_time=2)
        self.wait(2)
        self.play(Transform(function,funcc))
        self.wait(1)
        self.play(Unwrite(title))
        self.play(function.animate.to_edge(UL),sets.animate.to_edge(UR),seta.animate.to_edge(UR).shift(DOWN*0.7))


        n_txt = MathTex("n","=")
        n_val = always_redraw(lambda: DecimalNumber(n.get_value(),num_decimal_places=2,include_sign=True).set_color(MAROON).next_to(n_txt,RIGHT))
        n_values = VGroup(n_txt,n_val).to_edge(UR).set_color(MAROON).next_to(seta,DOWN)
        m_txt = MathTex("m","=")
        m_val = always_redraw(lambda: DecimalNumber(m.get_value(),num_decimal_places=2,include_sign=True).set_color(MAROON).next_to(m_txt,RIGHT))
        m_values = VGroup(m_txt,m_val).to_edge(UR).set_color(MAROON).next_to(n_values,DOWN)

        n_txt[0].set_color(TEAL)
        n_txt[1].set_color(WHITE)
        m_txt[0].set_color(TEAL)
        m_txt[1].set_color(WHITE)


        self.play(Transform(sets,sett))



        ot = Dot([0,0,0]).scale(0.25).set_color(GREEN)

        thet = MathTex(r"\frac{}{}\theta=2\pi k + \begin{cases}\arctan\left ( \frac{n}{x} \right ) & \text{ if } x> 0 \\ \frac{\pi }{2} & \text{ if } x=0 \\ \arctan\left ( \frac{n}{x} \right )+\pi & \text{ if } x< 0 \end{cases}")
        rad = MathTex(r"r=\sqrt{x^2+n^2}").shift(DOWN*3).set_color(ORANGE)

        cmplx = ComplexPlane(x_range=[-2.5,2.5],y_range=[-2.5,2.5])
        texx = MathTex(r"\operatorname{Re}").next_to(cmplx,RIGHT)
        texn = MathTex(r"\operatorname{Im}").next_to(cmplx,UP)

        texx.add_updater(lambda x: x.next_to(cmplx,RIGHT))
        texn.add_updater(lambda x: x.next_to(cmplx,UP))

        Odot = Dot([0,0,0])
        refdot = Dot([2,0,0]).set_opacity(0)
        dot = Dot([2,2,0])

        texa = MathTex(r"a").set_color(PURPLE)
        texa.add_updater(lambda x: x.next_to(dot,UR*0.5))

        refline = Line([2,0,0],[0,0,0])
        line = Line(Odot.get_center(), dot.get_center()).set_color(GREEN)

        crc = Circle().scale(2).rotate(PI/4)

        dashline = always_redraw(lambda: DashedLine(dot.get_center(),refdot.get_center()).set_color(YELLOW))
        dashline2 = DashedLine(refdot.get_center(),dot.get_center()).set_color(YELLOW)
        dashang = Angle(dashline2,refline,radius=0.25,dot=True).set_color(YELLOW)

        refline = Line([0,0,0],[2,0,0])
        
        self.play(Write(cmplx))
        self.play(Write(texx),Write(texn))
        self.play(Write(line),Write(ot),Write(dot))
        self.remove(line,dot,ot)
        self.add_foreground_mobjects(line,dot,ot)
        self.play(Write(texa))
        self.remove(texa)
        self.add_foreground_mobjects(texa)
        self.play(Write(dashline),run_time=0.5)
        self.remove(dashline)
        self.add(dashline2)
        self.wait(0.5)
        self.play(Write(dashang))

        cmpgraph = VGroup(texx,texn,cmplx,line,dot,ot,dashline2,texa)
        self.play(cmpgraph.animate.shift(UP/2),dashang.animate.shift(UP/2),FadeIn(rad,shift=UP*0.5))
        self.wait(1)
        self.play(line.animate.set_color(ORANGE),ot.animate.set_color(ORANGE))
        self.play(line.animate.set_color(GREEN),ot.animate.set_color(GREEN))
        self.wait(1)
        self.play(cmpgraph.animate.shift(DOWN/2),dashang.animate.shift(DOWN/2),FadeOut(rad,shift=DOWN*0.5))
        self.wait(1)

        self.play(Unwrite(dashang),run_time=0.5)        
        self.play(Unwrite(dashline2),run_time=0.5)
        self.wait(1)

        dot2 = Dot([0,0,0])

        rotation_center = [0,1,0]
        theta_tracker = ValueTracker(45)

        line1 = Line([0,1,0], [2*0.75,1,0])
        line_moving = Line([0,1,0], [2*0.75,1,0]).set_color(GREEN)
        line_moving_ref = Line([0,1,0], [4*0.75,1,0]).set_opacity(0)
        line_ref = line_moving.copy()
        line_ref_ref = line_moving_ref.copy()


        line_moving_ref.rotate(
            theta_tracker.get_value() * DEGREES, about_point=rotation_center
        )
        line_moving.rotate(
            theta_tracker.get_value() * DEGREES, about_point=rotation_center
        )
        
        ang = Angle(line1, line_moving, radius=0.5, other_angle=False).set_color(ORANGE)
        thet = MathTex(r"\theta").move_to(
            Angle(
                line1, line_moving, radius=0.5 + 3 * SMALL_BUFF, other_angle=False
            ).point_from_proportion(0.5)
        ).set_color(ORANGE)

        line_moving_ref.add_updater(
            lambda x: x.become(line_ref_ref.copy()).rotate(
                theta_tracker.get_value() * DEGREES, about_point=rotation_center
            )
        )
        
        dot2.add_updater(lambda x: x.move_to(line_moving_ref))

        line_moving.add_updater(
            lambda x: x.become(line_ref.copy()).rotate(
                theta_tracker.get_value() * DEGREES, about_point=rotation_center
            )
        )

        ang.add_updater(
            lambda x: x.become(Angle(line1, line_moving_ref, radius=0.5, other_angle=False)).set_color(ORANGE)
        )
        thet.add_updater(
            lambda x: x.move_to(
                Angle(
                    line1, line_moving, radius=0.5 + 3 * SMALL_BUFF, other_angle=False
                ).point_from_proportion(0.5)
            )
        )

        dot3 = Dot([2*np.cos(PI/4),2*np.cos(PI/4),0])
        line3 = Line([0,0,0],[2*np.cos(PI/4),2*np.cos(PI/4),0]).set_color(GREEN)

        myTemplate = TexTemplate()
        myTemplate.add_to_preamble(r"\usepackage{amsmath}")
        
        thetas = MathTex(r"\theta_{k}=\left\{\begin{alignedat}{2}&\! \arctan \left (\frac{n}{x}  \right )      &\qquad& \text{if $x>0$} \\& \operatorname{sgn}\left (n  \right ) \frac{\pi}{2}            &      & \text{if $x=0$} \\&\! \arctan \left (\frac{n}{x}  \right ) +\pi &      & \text{if $x<0$}\end{alignedat}\right\}+2\pi k ",tex_template=myTemplate).set_color(ORANGE).shift(DOWN*2.5).scale(0.75)

        self.play(Transform(dot,dot3),Transform(line,line3))
        self.remove(dot,line)
        self.add_foreground_mobjects(line3,dot3)
        self.wait(1)
        self.play(Create(crc))
        self.play(Unwrite(texa))
        self.wait(1)
        self.play(FadeIn(thetas[0][0],shift=UP),FadeIn(thetas[0][2:73],shift=UP),crc.animate.shift(UP).scale(0.75),cmplx.animate.shift(UP).scale(0.75),texx.animate.scale(0.75),texn.animate.scale(0.75),ot.animate.shift(UP).scale(0.75),Transform(line3,line_moving),Transform(dot3,dot2))
        self.play(Write(ang),Write(thet))
        self.remove(ang,thet,line3,dot3,line_moving,dot2)
        self.add_foreground_mobjects(line_moving_ref,ang,line_moving,thet,dot2)
        self.wait(1)

        self.play(theta_tracker.animate.set_value(60),thetas[0][14:30].animate.set_color(YELLOW),run_time=1)
        self.wait(2)
        self.play(theta_tracker.animate.set_value(315),run_time=1)
        self.wait(1)
        self.play(thetas[0][14:30].animate.set_color(ORANGE))
        self.play(theta_tracker.animate.set_value(90),thetas[0][30:44].animate.set_color(YELLOW),run_time=1)
        self.wait(2)
        self.play(theta_tracker.animate.set_value(270),run_time=1)
        self.wait(1)
        self.play(thetas[0][30:44].animate.set_color(ORANGE))
        self.play(theta_tracker.animate.set_value(120),thetas[0][44:62].animate.set_color(YELLOW),run_time=1)
        self.wait(2)
        self.play(theta_tracker.animate.set_value(240),run_time=1)
        self.wait(1)
        self.play(thetas[0][44:62].animate.set_color(ORANGE))
        
        
        self.play(Write(thetas[0][1]),Write(thetas[0][73:77]))
        
        
        self.play(theta_tracker.animate.set_value(45),thetas[0][73:77].animate.set_color(YELLOW),run_time=1)
        self.wait(2)
        self.play(theta_tracker.animate.set_value(45+360),run_time=1)
        self.wait(2)
        self.play(theta_tracker.animate.set_value(45+360*2),run_time=1)
        self.wait(1)
        self.play(thetas[0][73:77].animate.set_color(ORANGE))

        self.play(Unwrite(crc),Unwrite(ang),Unwrite(thet))
        self.play(Unwrite(line_moving),Unwrite(dot2),Unwrite(ot))
        self.play(FadeOut(thetas,shift=DOWN),Unwrite(cmplx),Unwrite(texx),Unwrite(texn))
        self.wait(1)






        y0 = MathTex("y","=").scale(0.8).next_to(func,DOWN).to_edge(LEFT)
        y0[0].set_color(BLUE)
        y0[1].set_color(GOLD)
        z0 = MathTex("z","=").scale(0.8).next_to(y0,DOWN).to_edge(LEFT)
        z0[0].set_color(BLUE)
        z0[1].set_color(GOLD)

        y1 = MathTex("y","=","x").scale(0.8).set_color(GOLD).next_to(function2,DOWN).to_edge(LEFT)
        y1[0].set_color(BLUE)
        z1 = MathTex("z","=","n").scale(0.8).set_color(GOLD).next_to(y1,DOWN).to_edge(LEFT)
        z1[0].set_color(BLUE)

        self.play(Write(y0),Write(z0),Transform(function,func))
        self.wait(1)

        functionb = MathTex(r"f(a)=|a|").to_edge(UL).set_color(PURPLE)
        functionb[0][0:2].set_color(GREEN)
        functionb[0][2:3].set_color(PURPLE)
        functionb[0][3:4].set_color(GREEN)
        functionb[0][4:5].set_color(WHITE)

        y2 = MathTex("y","=",r"r").scale(0.8).set_color(GOLD).next_to(functionb,DOWN).to_edge(LEFT)
        z2 = MathTex("z","=",r"0").scale(0.8).set_color(GOLD).next_to(y2,DOWN).to_edge(LEFT)
        y2[0].set_color(BLUE)
        z2[0].set_color(BLUE)

        function3 = MathTex(r"f(a)=\frac{1}{a}").to_edge(UL).set_color(PURPLE)
        function3[0][0:2].set_color(GREEN)
        function3[0][2:3].set_color(PURPLE)
        function3[0][3:4].set_color(GREEN)
        function3[0][4:5].set_color(WHITE)

        y3 = MathTex("y","=",r"\frac{x}{x^2+n^2}").scale(0.8).set_color(GOLD).next_to(function3,DOWN).to_edge(LEFT)
        z3 = MathTex("z","=",r"\frac{-n}{x^2+n^2}").scale(0.8).set_color(GOLD).next_to(y3,DOWN).to_edge(LEFT)
        y3[0].set_color(BLUE)
        z3[0].set_color(BLUE)

        function4 = MathTex(r"f(a)=a^2").to_edge(UL).set_color(PURPLE)
        function4[0][0:2].set_color(GREEN)
        function4[0][2:3].set_color(PURPLE)
        function4[0][3:4].set_color(GREEN)
        function4[0][4:5].set_color(WHITE)

        y4 = MathTex("y","=",r"x^2-n^2").scale(0.8).set_color(GOLD).next_to(function4,DOWN).to_edge(LEFT)
        z4 = MathTex("z","=",r"2xn").scale(0.8).set_color(GOLD).set_color(GOLD).next_to(y4,DOWN).to_edge(LEFT)
        y4[0].set_color(BLUE)
        z4[0].set_color(BLUE)

        function5 = MathTex(r"f(a)=a^3").to_edge(UL).set_color(PURPLE)
        function5[0][0:2].set_color(GREEN)
        function5[0][2:3].set_color(PURPLE)
        function5[0][3:4].set_color(GREEN)
        function5[0][4:5].set_color(WHITE)

        y5 = MathTex("y","=",r"x^3-3xn^2").scale(0.8).set_color(GOLD).next_to(function5,DOWN).to_edge(LEFT)
        z5 = MathTex("z","=",r"3nx^2-n^3").scale(0.8).set_color(GOLD).next_to(y5,DOWN).to_edge(LEFT)
        y5[0].set_color(BLUE)
        z5[0].set_color(BLUE)

        function6 = MathTex(r"f(a)=\sqrt{a}").to_edge(UL).set_color(PURPLE)
        function6[0][0:2].set_color(GREEN)
        function6[0][2:3].set_color(PURPLE)
        function6[0][3:4].set_color(GREEN)
        function6[0][4:5].set_color(WHITE)

        y6 = MathTex("y","=",r"\sqrt{r}\cos\left ( \frac{\theta}{2}  \right )").scale(0.75).set_color(GOLD).next_to(function6,DOWN).to_edge(LEFT)
        z6 = MathTex("z","=",r"\sqrt{r}\sin\left ( \frac{\theta}{2}  \right )").scale(0.75).set_color(GOLD).next_to(y6,DOWN).to_edge(LEFT)
        y6[0].set_color(BLUE)
        z6[0].set_color(BLUE)
        y6k = MathTex("y","=",r"\sqrt{r}\cos\left ( \frac{\theta_k}{2}  \right )").scale(0.75).set_color(GOLD).next_to(function6,DOWN).to_edge(LEFT)
        z6k = MathTex("z","=",r"\sqrt{r}\sin\left ( \frac{\theta_k}{2}  \right )").scale(0.75).set_color(GOLD).next_to(y6k,DOWN).to_edge(LEFT)
        y6k[0].set_color(BLUE)
        z6k[0].set_color(BLUE)

        function7 = MathTex(r"f(a)=\sqrt[3]{a}").to_edge(UL).set_color(PURPLE)
        function7[0][0:2].set_color(GREEN)
        function7[0][2:3].set_color(PURPLE)
        function7[0][3:4].set_color(GREEN)
        function7[0][4:5].set_color(WHITE)

        y7 = MathTex("y","=",r"\sqrt[3]{r}\cos\left ( \frac{\theta}{3}  \right )").scale(0.75).set_color(GOLD).next_to(function7,DOWN).to_edge(LEFT)
        z7 = MathTex("z","=",r"\sqrt[3]{r}\sin\left ( \frac{\theta}{3}  \right )").scale(0.75).set_color(GOLD).next_to(y7,DOWN).to_edge(LEFT)
        y7[0].set_color(BLUE)
        z7[0].set_color(BLUE)
        y7k = MathTex("y","=",r"\sqrt[3]{r}\cos\left ( \frac{\theta_k}{3}  \right )").scale(0.75).set_color(GOLD).next_to(function7,DOWN).to_edge(LEFT)
        z7k = MathTex("z","=",r"\sqrt[3]{r}\sin\left ( \frac{\theta_k}{3}  \right )").scale(0.75).set_color(GOLD).next_to(y7k,DOWN).to_edge(LEFT)
        y7k[0].set_color(BLUE)
        z7k[0].set_color(BLUE)

        function8 = MathTex(r"f(a,m)=a^m").to_edge(UL).set_color(PURPLE)
        function8[0][0:2].set_color(GREEN)
        function8[0][2:3].set_color(PURPLE)
        function8[0][3:4].set_color(GREEN)
        function8[0][4:5].set_color(PURPLE)
        function8[0][5:6].set_color(GREEN)
        function8[0][6:7].set_color(WHITE)

        y8 = MathTex("y","=",r"r^m\cos\left ( \theta m  \right )").scale(0.8).set_color(GOLD).next_to(function8,DOWN).to_edge(LEFT)
        z8 = MathTex("z","=",r"r^m\sin\left ( \theta m  \right )").scale(0.8).set_color(GOLD).next_to(y8,DOWN).to_edge(LEFT)
        y8[0].set_color(BLUE)
        z8[0].set_color(BLUE)

        function9 = MathTex(r"f(a)=e^a").to_edge(UL).set_color(PURPLE)
        function9[0][0:2].set_color(GREEN)
        function9[0][2:3].set_color(PURPLE)
        function9[0][3:4].set_color(GREEN)
        function9[0][4:5].set_color(WHITE)

        y9 = MathTex("y","=",r"e^x\cos(n)").scale(0.8).set_color(GOLD).next_to(function9,DOWN).to_edge(LEFT)
        z9 = MathTex("z","=",r"e^x\sin(n)").scale(0.8).set_color(GOLD).next_to(y9,DOWN).to_edge(LEFT)
        y9[0].set_color(BLUE)
        z9[0].set_color(BLUE)

        function10 = MathTex(r"f(a,m)=m^a").to_edge(UL).set_color(PURPLE)
        function10[0][0:2].set_color(GREEN)
        function10[0][2:3].set_color(PURPLE)
        function10[0][3:4].set_color(GREEN)
        function10[0][4:5].set_color(PURPLE)
        function10[0][5:6].set_color(GREEN)
        function10[0][6:7].set_color(WHITE)

        y10 = MathTex("y","=",r"e^{x\ln(m)}\cos(n\ln(m))").scale(0.8).set_color(GOLD).next_to(function10,DOWN).to_edge(LEFT)
        z10 = MathTex("z","=",r"e^{x\ln(m)}\sin(n\ln(m))").scale(0.8).set_color(GOLD).next_to(y10,DOWN).to_edge(LEFT)
        y10[0].set_color(BLUE)
        z10[0].set_color(BLUE)

        function11 = MathTex(r"f(a)=\ln(a)").to_edge(UL).set_color(PURPLE)
        function11[0][0:2].set_color(GREEN)
        function11[0][2:3].set_color(PURPLE)
        function11[0][3:4].set_color(GREEN)
        function11[0][4:5].set_color(WHITE)

        y11 = MathTex("y","=",r"\ln(r)").scale(0.8).set_color(GOLD).next_to(function11,DOWN).to_edge(LEFT)
        z11 = MathTex("z","=",r"\theta").scale(0.8).set_color(GOLD).next_to(y11,DOWN).to_edge(LEFT)
        y11[0].set_color(BLUE)
        z11[0].set_color(BLUE)
        y11k = MathTex("y","=",r"\ln(r)").scale(0.8).set_color(GOLD).next_to(function11,DOWN).to_edge(LEFT)
        z11k = MathTex("z","=",r"\theta_k").scale(0.8).set_color(GOLD).next_to(y11k,DOWN).to_edge(LEFT)
        y11k[0].set_color(BLUE)
        z11k[0].set_color(BLUE)

        function12 = MathTex(r"f(a,m)=\log_m(a)").to_edge(UL).set_color(PURPLE)
        function12[0][0:2].set_color(GREEN)
        function12[0][2:3].set_color(PURPLE)
        function12[0][3:4].set_color(GREEN)
        function12[0][4:5].set_color(PURPLE)
        function12[0][5:6].set_color(GREEN)
        function12[0][6:7].set_color(WHITE)

        y12 = MathTex("y","=",r"\frac{\ln(r)}{\ln(m)}").scale(0.8).set_color(GOLD).next_to(function12,DOWN).to_edge(LEFT)
        z12 = MathTex("z","=",r"\frac{\theta}{\ln(m)}").scale(0.8).set_color(GOLD).next_to(y12,DOWN).to_edge(LEFT)
        y12[0].set_color(BLUE)
        z12[0].set_color(BLUE)

        function13 = MathTex(r"f(a)=\sin(a)").to_edge(UL).set_color(PURPLE)
        function13[0][0:2].set_color(GREEN)
        function13[0][2:3].set_color(PURPLE)
        function13[0][3:4].set_color(GREEN)
        function13[0][4:5].set_color(WHITE)

        y13 = MathTex("y","=",r"\sin(x)\cosh(n)").scale(0.8).set_color(GOLD).next_to(function13,DOWN).to_edge(LEFT)
        z13 = MathTex("z","=",r"\cos(x)\sinh(n)").scale(0.8).set_color(GOLD).next_to(y13,DOWN).to_edge(LEFT)
        y13[0].set_color(BLUE)
        z13[0].set_color(BLUE)

        function14 = MathTex(r"f(a)=\cos(a)").to_edge(UL).set_color(PURPLE)
        function14[0][0:2].set_color(GREEN)
        function14[0][2:3].set_color(PURPLE)
        function14[0][3:4].set_color(GREEN)
        function14[0][4:5].set_color(WHITE)

        y14 = MathTex("y","=",r"\cos(x)\cosh(n)").scale(0.8).set_color(GOLD).next_to(function14,DOWN).to_edge(LEFT)
        z14 = MathTex("z","=",r"-\sin(x)\sinh(n)").scale(0.8).set_color(GOLD).next_to(y14,DOWN).to_edge(LEFT)
        y14[0].set_color(BLUE)
        z14[0].set_color(BLUE)

        function15 = MathTex(r"f(a)=\tan(a)").to_edge(UL).set_color(PURPLE)
        function15[0][0:2].set_color(GREEN)
        function15[0][2:3].set_color(PURPLE)
        function15[0][3:4].set_color(GREEN)
        function15[0][4:5].set_color(WHITE)

        y15 = MathTex("y","=",r"\frac{\sin(2x)}{\cos(2x)+\cosh(2n)}").scale(0.65).set_color(GOLD).next_to(function15,DOWN).to_edge(LEFT)
        z15 = MathTex("z","=",r"\frac{\sinh(2n)}{\cos(2x)+\cosh(2n)}").scale(0.65).set_color(GOLD).next_to(y15,DOWN).to_edge(LEFT)
        y15[0].set_color(BLUE)
        z15[0].set_color(BLUE)

        function16 = MathTex(r"f(a)=\sinh(a)").to_edge(UL).set_color(PURPLE)
        function16[0][0:2].set_color(GREEN)
        function16[0][2:3].set_color(PURPLE)
        function16[0][3:4].set_color(GREEN)
        function16[0][4:5].set_color(WHITE)

        y16 = MathTex("y","=",r"\cos(n)\sinh(x)").scale(0.8).set_color(GOLD).next_to(function16,DOWN).to_edge(LEFT)
        z16 = MathTex("z","=",r"\sin(n)\cosh(x)").scale(0.8).set_color(GOLD).next_to(y16,DOWN).to_edge(LEFT)
        y16[0].set_color(BLUE)
        z16[0].set_color(BLUE)

        function17 = MathTex(r"f(a)=\cosh(a)").to_edge(UL).set_color(PURPLE)
        function17[0][0:2].set_color(GREEN)
        function17[0][2:3].set_color(PURPLE)
        function17[0][3:4].set_color(GREEN)
        function17[0][4:5].set_color(WHITE)

        y17 = MathTex("y","=",r"\cos(n)\cosh(x)").scale(0.8).set_color(GOLD).next_to(function17,DOWN).to_edge(LEFT)
        z17 = MathTex("z","=",r"\sin(n)\sinh(x)").scale(0.8).set_color(GOLD).next_to(y17,DOWN).to_edge(LEFT)
        y17[0].set_color(BLUE)
        z17[0].set_color(BLUE)

        function18 = MathTex(r"f(a)=\tanh(a)").to_edge(UL).set_color(PURPLE)
        function18[0][0:2].set_color(GREEN)
        function18[0][2:3].set_color(PURPLE)
        function18[0][3:4].set_color(GREEN)
        function18[0][4:5].set_color(WHITE)

        y18 = MathTex("y","=",r"\frac{\sinh(2x)}{\cos(2n)+\cosh(2x)}").scale(0.65).set_color(GOLD).next_to(function18,DOWN).to_edge(LEFT)
        z18 = MathTex("z","=",r"\frac{\sin(2n)}{\cos(2n)+\cosh(2x)}").scale(0.65).set_color(GOLD).next_to(y18,DOWN).to_edge(LEFT)
        y18[0].set_color(BLUE)
        z18[0].set_color(BLUE)        

        function19 = MathTex(r"f(a)=a^a").to_edge(UL).set_color(PURPLE)
        function19[0][0:2].set_color(GREEN)
        function19[0][2:3].set_color(PURPLE)
        function19[0][3:4].set_color(GREEN)
        function19[0][4:5].set_color(WHITE)

        y19 = MathTex("y","=",r"r^ae^{-\theta n}\cos(\theta x)").scale(0.8).set_color(GOLD).next_to(function19,DOWN).to_edge(LEFT)
        z19 = MathTex("z","=",r"r^ae^{-\theta n}\sin(\theta x)").scale(0.8).set_color(GOLD).next_to(y19,DOWN).to_edge(LEFT)
        y19[0].set_color(BLUE)
        z19[0].set_color(BLUE)
        y19k = MathTex("y","=",r"r^ae^{-\theta_k n}\cos(\theta_k x)").scale(0.8).set_color(GOLD).next_to(function19,DOWN).to_edge(LEFT)
        z19k = MathTex("z","=",r"r^ae^{-\theta_k n}\sin(\theta_k x)").scale(0.8).set_color(GOLD).next_to(y19k,DOWN).to_edge(LEFT)
        y19k[0].set_color(BLUE)
        z19k[0].set_color(BLUE)

        function20 = MathTex(r"f(a)=a!").to_edge(UL).set_color(PURPLE)
        function20[0][0:2].set_color(GREEN)
        function20[0][2:3].set_color(PURPLE)
        function20[0][3:4].set_color(GREEN)
        function20[0][4:5].set_color(WHITE)

        y20 = MathTex("y","=",r"\operatorname{Re}(\Gamma(a+1))").scale(0.8).set_color(GOLD).next_to(function20,DOWN).to_edge(LEFT)
        z20 = MathTex("z","=",r"\operatorname{Im}(\Gamma(a+1))").scale(0.8).set_color(GOLD).next_to(y20,DOWN).to_edge(LEFT)
        y20[0].set_color(BLUE)
        z20[0].set_color(BLUE)




        self.play(Transform(y0,y1),Transform(z0,z1),Transform(function,function2),Write(n_values),run_time=1)
        self.wait(2)

        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y2),Transform(z0,z2),Transform(function,functionb))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(5))
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(1)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y3),Transform(z0,z3),Transform(function,function3))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(0.3))
        self.play(n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-0.3))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        

        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y4),Transform(z0,z4),Transform(function,function4))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(-2),run_time=2)
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y5),Transform(z0,z5),Transform(function,function5))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(1))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(1))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y6),Transform(z0,z6),Transform(function,function6))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y6k),Transform(z0,z6k),Transform(function,function6),Transform(sets,setk))
        self.wait(1)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y6),Transform(z0,z6),Transform(function,function6),Transform(sets,sett))
        self.wait(1)
        self.play(Transform(y0,y7),Transform(z0,z7),Transform(function,function7))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y7k),Transform(z0,z7k),Transform(function,function7),Transform(sets,setk))
        self.wait(1)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y7),Transform(z0,z7),Transform(function,function7),Transform(sets,sett))
        self.wait(1)
        self.play(Transform(y0,y8),Transform(z0,z8),Transform(function,function8))
        self.play(Write(m_values),Transform(sets,setsm))
        self.wait(1)



        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),m.animate.set_value(0.5))
        self.wait(1)
        self.play(n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(1))
        self.wait(1)
        self.play(m.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(-1),run_time=2)
        self.wait(1)
        self.play(m.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.wait(1)
        self.play(m.animate.set_value(-3))
        self.wait(1)
        self.play(m.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(4))
        self.wait(1)
        self.play(m.animate.set_value(6))
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=2)
        self.play(m.animate.set_value(1))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(m.animate.set_value(1.5))
        self.wait(1)
        self.play(m.animate.set_value(2.5))
        self.wait(1)
        self.play(m.animate.set_value(4))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.wait(1)
        self.play(m.animate.set_value(-4),run_time=3)
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),m.animate.set_value(0),run_time=3)
        self.wait(1)
        self.play(m.animate.set_value(0.5))
        self.wait(1)
        self.play(m.animate.set_value(2.5))
        self.wait(1)
        self.play(m.animate.set_value(-3),run_time=3)
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.wait(1)
        self.play(m.animate.set_value(2))
        self.play(m.animate.set_value(3))
        self.play(m.animate.set_value(4))
        self.play(m.animate.set_value(5))
        self.play(m.animate.set_value(6))
        self.play(m.animate.set_value(1),n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y9),Transform(z0,z9),Transform(function,function9))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(PI))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-PI))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(PI))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-PI))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y10),Transform(z0,z10),Transform(function,function10))
        self.wait(2)

        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),m.animate.set_value(3))
        self.wait(1)
        self.play(m.animate.set_value(0.3))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(m.animate.set_value(3))
        self.wait(1)
        self.play(m.animate.set_value(0.3))
        self.wait(1)
        self.play(m.animate.set_value(0))
        self.wait(2)
        self.play(m.animate.set_value(-1),run_time=2)
        self.wait(1)
        self.play(n.animate.set_value(0.5))
        self.wait(1)
        self.play(n.animate.set_value(-0.5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(-1.3))
        self.wait(1)
        self.play(n.animate.set_value(0.5))
        self.wait(1)
        self.play(n.animate.set_value(-0.5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(-1))
        self.wait(1)
        
        self.wait(2)
        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(0.5))
        self.wait(1)
        self.play(n.animate.set_value(-0.5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(-1.3))
        self.wait(1)
        self.play(n.animate.set_value(0.5))
        self.wait(1)
        self.play(n.animate.set_value(-0.5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(-1))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(0.5))
        self.wait(1)
        self.play(n.animate.set_value(-0.5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(-1.3))
        self.wait(1)
        self.play(n.animate.set_value(0.5))
        self.wait(1)
        self.play(n.animate.set_value(-0.5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(-1))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y11),Transform(z0,z11),Transform(function,function11))
        self.wait(2)

        
        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y11k),Transform(z0,z11k),Transform(sets,setkl))
        self.wait(1)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-5))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(Transform(y0,y11),Transform(z0,z11),Transform(sets,setsm))
        self.wait(1)
        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.play(m.animate.set_value(np.e))
        self.play(Transform(y0,y12),Transform(z0,z12),Transform(function,function12))
        self.wait(1)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),m.animate.set_value(4))
        self.wait(1)
        self.play(m.animate.set_value(np.e))
        self.wait(1)
        self.play(m.animate.set_value(1))
        self.play(m.animate.set_value(0.3))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.play(m.animate.set_value(0.3))
        self.wait(1)
        self.play(m.animate.set_value(1))
        self.play(m.animate.set_value(np.e))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(m.animate.set_value(4))
        self.wait(1)
        self.play(m.animate.set_value(np.e))
        self.wait(1)
        self.play(m.animate.set_value(1))
        self.play(m.animate.set_value(0.3))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.play(m.animate.set_value(0.3))
        self.wait(1)
        self.play(m.animate.set_value(1))
        self.play(m.animate.set_value(np.e))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),m.animate.set_value(4))
        self.wait(1)
        self.play(m.animate.set_value(np.e))
        self.wait(1)
        self.play(m.animate.set_value(1))
        self.play(m.animate.set_value(0.3))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.play(m.animate.set_value(0.3))
        self.wait(1)
        self.play(m.animate.set_value(1))
        self.play(m.animate.set_value(np.e))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(m.animate.set_value(0))
        self.wait(1)
        self.play(m.animate.set_value(-1))
        self.wait(1)
        self.play(m.animate.set_value(-3))
        self.wait(1)
        self.play(m.animate.set_value(-1))
        self.play(m.animate.set_value(-0.1))
        self.wait(1)
        self.play(m.animate.set_value(-1))
        self.wait(1)
        self.play(n.animate.set_value(0.1))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.wait(2)
        self.play(Transform(y0,y13),Transform(z0,z13),Transform(function,function13),Unwrite(m_values),Transform(sets,sett))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y14),Transform(z0,z14),Transform(function,function14))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-2))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y15),Transform(z0,z15),Transform(function,function15))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(1))
        self.play(n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.play(n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(1))
        self.play(n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y16),Transform(z0,z16),Transform(function,function16))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(3))
        self.play(n.animate.set_value(5))
        self.play(n.animate.set_value(7))
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=2)
        self.play(n.animate.set_value(-3))
        self.play(n.animate.set_value(-5))
        self.play(n.animate.set_value(-7))
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=2)
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y17),Transform(z0,z17),Transform(function,function17))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(3))
        self.play(n.animate.set_value(5))
        self.play(n.animate.set_value(7))
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=2)
        self.play(n.animate.set_value(-3))
        self.play(n.animate.set_value(-5))
        self.play(n.animate.set_value(-7))
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=2)
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-3))
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y18),Transform(z0,z18),Transform(function,function18))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(1))
        self.play(n.animate.set_value(2))
        self.play(n.animate.set_value(6),run_time=5)
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-2))
        self.play(n.animate.set_value(-6),run_time=5)
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.play(n.animate.set_value(2))
        self.play(n.animate.set_value(6),run_time=5)
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-2))
        self.play(n.animate.set_value(-6),run_time=5)
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(1))
        self.play(n.animate.set_value(2))
        self.play(n.animate.set_value(6),run_time=5)
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-2))
        self.play(n.animate.set_value(-6),run_time=5)
        self.wait(1)
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y19),Transform(z0,z19),Transform(function,function19))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(1))
        self.play(n.animate.set_value(2.5))
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-2.5))
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(1))
        self.play(n.animate.set_value(2.5))
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-2.5))
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(1))
        self.play(n.animate.set_value(2.5))
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-1))
        self.play(n.animate.set_value(-2.5))
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Transform(y0,y19k),Transform(z0,z19k),Transform(sets,setkp))
        self.wait(7.5)

        self.play(n.animate.set_value(0.1))
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-0.1))
        self.play(n.animate.set_value(0))
        self.wait(1)

        self.wait(3)
        self.play(Transform(sets,setkm))
        self.wait(5.5)

        self.play(n.animate.set_value(0.1))
        self.play(n.animate.set_value(0))
        self.play(n.animate.set_value(-0.1))
        self.play(n.animate.set_value(0))
        self.wait(1)


        self.wait(2)
        self.play(Transform(y0,y20),Transform(z0,z20),Transform(function,function20),Transform(sets,sett))
        self.wait(2)


        self.play(y0[0].animate.set_color(YELLOW),y0[1].animate.set_color(YELLOW),y0[2].animate.set_color(YELLOW),n.animate.set_value(0.1))
        self.play(n.animate.set_value(1),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(2),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(3),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(5),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=1.5)
        self.wait(1)

        self.play(y0[0].animate.set_color(BLUE),y0[1].animate.set_color(GOLD),y0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(n.animate.set_value(0.1),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(1),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(5),run_time=3)
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=2)
        self.wait(1)

        self.wait(2)
        self.play(n.animate.set_value(0.1),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(1),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(5),run_time=3)
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=2)
        self.wait(2)

        self.wait(2)
        self.play(z0[0].animate.set_color(YELLOW),z0[1].animate.set_color(YELLOW),z0[2].animate.set_color(YELLOW),n.animate.set_value(0.1))
        self.wait(1)
        self.play(n.animate.set_value(1),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(2),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(3),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(5),run_time=1)
        self.wait(1)
        self.play(n.animate.set_value(0),run_time=1.5)
        self.wait(1)


        self.play(z0[0].animate.set_color(BLUE),z0[1].animate.set_color(GOLD),z0[2].animate.set_color(GOLD))
        self.wait(1)
        self.play(Unwrite(function),Unwrite(sets),Unwrite(seta),Unwrite(n_values),Unwrite(y0),Unwrite(z0),run_time=3)
        self.wait(1)

        # manim -pqh youtube.py Inicio